version: '3.7'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/application
      - /application/node_modules
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017
      REDIS_HOST: redis://redis:6379
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    image: redis:6.2.6
